---
version: 3

images:
  base_image: 'registry.fedoraproject.org/fedora:39'

additional_build_files:
  - src: ansible.cfg
    dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg ~/.ansible.cfg

  append:
    - "RUN mkdir -p /usr/share/ansible/plugins"
    # yamllint disable-line rule:line-length
    - "RUN ln -s $(pip show mitogen | grep \"Location\" | sed  \"s/Location\\: //g\")/ansible_mitogen/plugins/strategy/ /usr/share/ansible/plugins/strategy"
