---
collections:
  - name: ansible.posix
    version: 1.5.4
    
  - name: community.aws
    version: 7.0.0

  - name: community.crypto
    version: 2.15.1

  - name: community.docker
    version: 3.4.8

  - name: community.general
    version: 8.1.0

  - name: community.grafana
    version: 1.6.1
   
  - name: hetzner.hcloud
    version: 2.1.1

  - name: community.kubernetes
    version: 2.0.1

  - name: community.mysql
    version: 3.7.2

  - name: containers.podman
    version: 1.10.3

  - name: community.postgresql
    version: 3.2.0
