---
collections:
  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com
    
  - name: community.aws
    version: 6.3.0
    source: https://galaxy.ansible.com

  - name: community.crypto
    version: 2.15.1
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 3.4.8
    source: https://galaxy.ansible.com

  - name: community.general
    version: 7.3.0
    source: https://galaxy.ansible.com

  - name: community.grafana
    version: 1.5.4
    source: https://galaxy.ansible.com
   
  - name: hetzner.hcloud
    version: 2.1.1
    source: https://galaxy.ansible.com

  - name: community.kubernetes
    version: 2.0.1
    source: https://galaxy.ansible.com

  - name: community.mysql
    version: 3.7.2
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.10.3
    source: https://galaxy.ansible.com

  - name: community.postgresql
    version: 3.2.0
    source: https://galaxy.ansible.com
