---
collections:
  - name: ansible.posix
    version: 2.0.0
    
  - name: community.aws
    version: 9.0.0

  - name: community.crypto
    version: 2.24.0

  - name: community.docker
    version: 4.3.1

  - name: community.general
    version: 10.2.0

  - name: community.grafana
    version: 2.1.0
   
  - name: hetzner.hcloud
    version: 4.2.2

  - name: community.kubernetes
    version: 2.0.1

  - name: community.mysql
    version: 3.12.0

  - name: containers.podman
    version: 1.16.2

  - name: community.postgresql
    version: 3.10.2
