---
collections:
  - name: ansible.posix
    version: 1.4.0
    source: https://galaxy.ansible.com
    
  - name: community.aws
    version: 4.1.1
    source: https://galaxy.ansible.com

  - name: community.crypto
    version: 2.5.0
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 3.0.2
    source: https://galaxy.ansible.com

  - name: community.general
    version: 5.4.0
    source: https://galaxy.ansible.com

  - name: community.grafana
    version: 1.5.2
    source: https://galaxy.ansible.com
   
  - name: hetzner.hcloud
    version: 1.8.1
    source: https://galaxy.ansible.com

  - name: community.kubernetes
    version: 2.0.1
    source: https://galaxy.ansible.com

  - name: community.mysql
    version: 3.4.0
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.9.4
    source: https://galaxy.ansible.com

  - name: community.postgresql
    version: 2.2.0
    source: https://galaxy.ansible.com
