---
collections:
  - name: ansible.posix
    version: 1.3.0
    source: https://galaxy.ansible.com
    
  - name: community.aws
    version: 3.2.1
    source: https://galaxy.ansible.com

  - name: community.crypto
    version: 2.2.4
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 2.4.0
    source: https://galaxy.ansible.com

  - name: community.general
    version: 4.8.0
    source: https://galaxy.ansible.com

  - name: community.grafana
    version: 1.4.0
    source: https://galaxy.ansible.com

  - name: community.kubernetes
    version: 2.0.1
    source: https://galaxy.ansible.com

  - name: community.mysql
    version: 3.1.3
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.9.3
    source: https://galaxy.ansible.com

  - name: community.postgresql
    version: 2.1.4
    source: https://galaxy.ansible.com
