---
collections:
  - name: ansible.posix
    version: 1.5.4
    
  - name: community.aws
    version: 7.2.0

  - name: community.crypto
    version: 2.19.1

  - name: community.docker
    version: 3.9.0

  - name: community.general
    version: 8.6.0

  - name: community.grafana
    version: 1.8.0
   
  - name: hetzner.hcloud
    version: 3.1.1

  - name: community.kubernetes
    version: 2.0.1

  - name: community.mysql
    version: 3.9.0

  - name: containers.podman
    version: 1.13.0

  - name: community.postgresql
    version: 3.4.0
