---
collections:
  - name: ansible.posix
    version: 1.5.4
    
  - name: community.aws
    version: 8.0.0

  - name: community.crypto
    version: 2.22.3

  - name: community.docker
    version: 3.13.2

  - name: community.general
    version: 9.5.1

  - name: community.grafana
    version: 2.1.0
   
  - name: hetzner.hcloud
    version: 4.2.1

  - name: community.kubernetes
    version: 2.0.1

  - name: community.mysql
    version: 3.9.0

  - name: containers.podman
    version: 1.15.4

  - name: community.postgresql
    version: 3.8.0
