---
collections:
  - name: ansible.posix
    version: 1.4.0
    source: https://galaxy.ansible.com
    
  - name: community.aws
    version: 5.0.0
    source: https://galaxy.ansible.com

  - name: community.crypto
    version: 2.8.0
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 3.1.0
    source: https://galaxy.ansible.com

  - name: community.general
    version: 5.8.0
    source: https://galaxy.ansible.com

  - name: community.grafana
    version: 1.5.3
    source: https://galaxy.ansible.com
   
  - name: hetzner.hcloud
    version: 1.8.2
    source: https://galaxy.ansible.com

  - name: community.kubernetes
    version: 2.0.1
    source: https://galaxy.ansible.com

  - name: community.mysql
    version: 3.5.1
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.9.4
    source: https://galaxy.ansible.com

  - name: community.postgresql
    version: 2.2.0
    source: https://galaxy.ansible.com
