---
name: Build ansible ee image
on:
  push:
    branches:
      - main
  schedule:
    - cron: "42 3 * * 4"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ci requirements
        run: pip install -r requirements-ci.txt

      - name: Build image
        run: ansible-builder build -v 3 -t ansible-ee:latest

      - name: Push ansible ee to ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ansible-ee
          tags: latest
          registry: ghcr.io/${{ github.repository_owner }}/
          username: ${{ github.actor }}
          password: ${{ github.token }}
